name: naja-action
on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run naja-action
        uses: keplertech/kepler-formal-action@main
        with:
          design_config: "oss_eda/yosys.ys"
        env:
          CVA6_REPO_DIR: "${{ github.workspace }}"
          HPDCACHE_DIR: "${{ github.workspace }}/core/cache_subsystem/hpdcache"
          TARGET_CFG: "cv64a6_imafdc_sv39"

      #- name: Run naja-action
      #  uses: xtofalex/naja-action@main
      #  with:
      #    mode: "orfs"
      #    design_config: "oss-eda/config.mk"
      #  env:
      #    CVA6_REPO_DIR: "${{ github.workspace }}"
